---
dependency:
  name: gilt
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: winlogbeat
    box: mwrock/Windows2016
    memory: 2048
    cpus: 2
    provider_options:
      gui: false
provisioner:
  name: ansible
  connection_options:
    ansible_connection: winrm
    ansible_port: 55985
    ansible_host: 127.0.0.1
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_winrm_scheme: http
    ansible_winrm_transport: ntlm
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: inspec
  lint:
    name: rubocop
