---
- name: Verify
  hosts: all
  vars:
    inspec_bin: ~/bin/inspec
    inspec_test_directory: "{{ molecule_scenario_directory }}/tests"
  tasks:
    - block:
        - name: Register test files
          find:
            path: "{{ inspec_test_directory }}"
            patterns: "*.rb"
          register: test_files

        - name: Execute Inspec tests
          command: "{{ inspec_bin }} exec {{ item.path }} -t {{ ansible_connection }}://{{ ansible_user }}@{{ ansible_host }} -p {{ ansible_port }} --password '{{ ansible_password }}'"
          register: test_results
          with_items: "{{ test_files.files }}"
          ignore_errors: true

        - name: Display details about the Inspec results
          debug:
            msg: "{{ item.stdout_lines }}"
          with_items: "{{ test_results.results }}"

        - name: Fail when tests fail
          fail:
            msg: "Inspec failed to validate"
          when: item.rc != 0
          with_items: "{{ test_results.results }}"
      delegate_to: localhost
